<?php

/**
 * Implements hook_permission().
 */
function bubblesort_permission() {
  return array(
    'use bubblesort' => array(
      'title' => t('Use Bubble Sort Similation'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function bubblesort_menu() {
  $items['bubblesort'] = array(
    'title' => 'Bubble Sort Simulation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bubblesort_form'),
    'access arguments' => array('bubblesort'),
  );

  return $items;
}

/**
 * Returns random array[0..9] of values 0..100.
 */
function _bubblesort_shuffle() {
  $arr = array();
  for ($i = 0; $i < 10; $i++) {
    $arr[] = rand(0, 100);
  }
  return $arr;
}

/**
 * Swaps two values in the array.
 */
function _bubblesort_swap(&$arr, $a, $b) {
  $tmp = $arr[$a];
  $arr[$a] = $arr[$b];
  $arr[$b] = $tmp;
}

/**
 * Checks if we need to swap.
 */
function _bubblesort_to_swap(&$arr, &$i, &$j) {
  return $arr[$j+1] < $arr[$j];
}

/**
 * Runs bubble sort iteration.
 */
function _bubblesort_step(&$arr, &$i, &$j) {

  // Compares two values.
  if (_bubblesort_to_swap($arr, $i, $j)) {
    _bubblesort_swap($arr, $j, $j+1, $log);
  }

  // Iterates.
  $j++;
  if ($j >= count($arr) - $i - 1) {
    $j = 0; $i++;
  }
  if ($i >= count($arr)) {
    return FALSE;
  }
  return TRUE;
}

/**
 * Watch data.
 */
function _bubblesort_watch(&$arr, &$i, &$j) {
  return array(
    'index' => $j,
    'current' => isset($arr[$j]) ? $arr[$j] : 'n/a',
    'next' => isset($arr[$j+1]) ? $arr[$j+1] : 'n/a',
    'to_swap' =>  isset($arr[$j]) &&  isset($arr[$j+1]) ? _bubblesort_to_swap($arr, $i, $j) : 'n/a'
  );
}

function bubblesort_form($form, &$form_state) {
  drupal_add_css(drupal_get_path('module', 'bubblesort') . '/bubblesort.css');

  $form = array();

  $in_progress = true; 
  $form_state['storage'] = empty($form_state['storage']) ? array() : $form_state['storage'];
  $s =& $form_state['storage'];
  $op = empty($form_state['values']['op']) ? '' : $form_state['values']['op'];

  if (empty($s) || $op == t('Shuffle')) {
    $s['arr'] = _bubblesort_shuffle();
    $s['i'] = 0;
    $s['j'] = 0;
    $s['watch'] = _bubblesort_watch($s['arr'], $s['i'], $s['j']);
  }

  if ($op == t('Step')) {
    $in_progress = _bubblesort_step($s['arr'], $s['i'], $s['j']);
    $s['watch'] = _bubblesort_watch($s['arr'], $s['i'], $s['j']);
  }

  $form['bubblesort'] = array(
    '#type' => 'container',
    '#prefix' => '<div id="bubblesort">',
    '#suffix' => '</div>',
  );

  $form['bubblesort']['index'] = array(
    '#title' => t('index'),
    '#type' => 'textfield',
    '#value' => $s['watch']['index'],
    '#disabled' => 'true'
  );

  $form['bubblesort']['current'] = array(
    '#title' => t('Current'),
    '#type' => 'textfield',
    '#value' => $s['watch']['current'],
    '#disabled' => 'true'
  );

  $form['bubblesort']['next'] = array(
    '#title' => t('Next'),
    '#type' => 'textfield',
    '#value' => $s['watch']['next'],
    '#disabled' => 'true'
  );

  $form['bubblesort']['to_swap'] = array(
    '#title' => t('Will be swaped'),
    '#type' => 'textfield',
    '#value' => $s['watch']['to_swap'] ? 'true' : 'false',
    '#disabled' => 'true'
  );

  $options = array();
  foreach ($s['arr'] as $key => $value) {
    $options[$key] = $key . ': ' . $value;
  }

  $chart = array(
    '#chart_id' => 'test_chart',
    '#type' => CHART_TYPE_BAR_V_GROUPED,
    '#title' => '',
    '#size' => array(
      '#width' => 300,
      '#height' => 180
    ),
  );

  $color_a = chart_unique_color('color_a');
  $color_b = chart_unique_color('color_b');

  foreach ($s['arr'] as $key => $el) {
    $chart['#data'][] = array($el);
    $chart['#data_colors'][] = $key == $s['watch']['index'] ? $color_a : $color_b;
  }

  $form['bubblesort']['chart'] = array(
    '#type' => 'markup',
    '#markup' => theme('chart', array('chart' => $chart))
  );


  //Build the tableselect.
  $form['bubblesort']['arr'] = array(
    '#type' => 'select',
    '#options' => $options,
    '#disabled' => TRUE,
    '#multiple' => FALSE,
    '#size' => 10,
    '#value' => $s['watch']['index']
  );


  $form['bubblesort']['shuffle'] = array(
    '#type' => 'submit',
    '#value' => t('Shuffle'),
    '#executes_submit_callback' => false,
    '#ajax' => array(
      'callback' => 'bubblesort_form_ajax',
      'wrapper' => 'bubblesort',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );

  $form['bubblesort']['step'] = array(
    '#type' => 'submit',
    '#value' => t('Step'),
    '#executes_submit_callback' => false,
    '#ajax' => array(
      'callback' => 'bubblesort_form_ajax',
      'wrapper' => 'bubblesort',
      'method' => 'replace',
      'effect' => 'fade',
    ),
    '#disabled' => !$in_progress
  );

  return $form;
}

function bubblesort_form_ajax($form, &$form_state) {
  return $form['bubblesort'];
}

function bubblesort_form_submit($form, &$form_state) {

}

